name: statosv1
description: A new Flutter project for StatOS MVP
publish_to: "none" # Remove this if you plan to publish on pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase for authentication and database
  supabase_flutter: ^2.10.0

  # Core Flutter libraries
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
